// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.2
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RealtimeConfigGrpcService_GetConfig_FullMethodName       = "/konfigo.client.RealtimeConfigGrpcService/GetConfig"
	RealtimeConfigGrpcService_IsVersionExists_FullMethodName = "/konfigo.client.RealtimeConfigGrpcService/IsVersionExists"
	RealtimeConfigGrpcService_CreateVersion_FullMethodName   = "/konfigo.client.RealtimeConfigGrpcService/CreateVersion"
	RealtimeConfigGrpcService_StartSubscribe_FullMethodName  = "/konfigo.client.RealtimeConfigGrpcService/StartSubscribe"
)

// RealtimeConfigGrpcServiceClient is the client API for RealtimeConfigGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RealtimeConfigGrpcServiceClient interface {
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	IsVersionExists(ctx context.Context, in *IsVersionExistRequest, opts ...grpc.CallOption) (*IsVersionExistResponse, error)
	CreateVersion(ctx context.Context, in *CreateVersionRequest, opts ...grpc.CallOption) (*CreateVersionResponse, error)
	StartSubscribe(ctx context.Context, in *StartSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscriptionEvent], error)
}

type realtimeConfigGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRealtimeConfigGrpcServiceClient(cc grpc.ClientConnInterface) RealtimeConfigGrpcServiceClient {
	return &realtimeConfigGrpcServiceClient{cc}
}

func (c *realtimeConfigGrpcServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, RealtimeConfigGrpcService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realtimeConfigGrpcServiceClient) IsVersionExists(ctx context.Context, in *IsVersionExistRequest, opts ...grpc.CallOption) (*IsVersionExistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsVersionExistResponse)
	err := c.cc.Invoke(ctx, RealtimeConfigGrpcService_IsVersionExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realtimeConfigGrpcServiceClient) CreateVersion(ctx context.Context, in *CreateVersionRequest, opts ...grpc.CallOption) (*CreateVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVersionResponse)
	err := c.cc.Invoke(ctx, RealtimeConfigGrpcService_CreateVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realtimeConfigGrpcServiceClient) StartSubscribe(ctx context.Context, in *StartSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscriptionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RealtimeConfigGrpcService_ServiceDesc.Streams[0], RealtimeConfigGrpcService_StartSubscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartSubscribeRequest, SubscriptionEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RealtimeConfigGrpcService_StartSubscribeClient = grpc.ServerStreamingClient[SubscriptionEvent]

// RealtimeConfigGrpcServiceServer is the server API for RealtimeConfigGrpcService service.
// All implementations must embed UnimplementedRealtimeConfigGrpcServiceServer
// for forward compatibility.
type RealtimeConfigGrpcServiceServer interface {
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	IsVersionExists(context.Context, *IsVersionExistRequest) (*IsVersionExistResponse, error)
	CreateVersion(context.Context, *CreateVersionRequest) (*CreateVersionResponse, error)
	StartSubscribe(*StartSubscribeRequest, grpc.ServerStreamingServer[SubscriptionEvent]) error
	mustEmbedUnimplementedRealtimeConfigGrpcServiceServer()
}

// UnimplementedRealtimeConfigGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRealtimeConfigGrpcServiceServer struct{}

func (UnimplementedRealtimeConfigGrpcServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedRealtimeConfigGrpcServiceServer) IsVersionExists(context.Context, *IsVersionExistRequest) (*IsVersionExistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsVersionExists not implemented")
}
func (UnimplementedRealtimeConfigGrpcServiceServer) CreateVersion(context.Context, *CreateVersionRequest) (*CreateVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVersion not implemented")
}
func (UnimplementedRealtimeConfigGrpcServiceServer) StartSubscribe(*StartSubscribeRequest, grpc.ServerStreamingServer[SubscriptionEvent]) error {
	return status.Error(codes.Unimplemented, "method StartSubscribe not implemented")
}
func (UnimplementedRealtimeConfigGrpcServiceServer) mustEmbedUnimplementedRealtimeConfigGrpcServiceServer() {
}
func (UnimplementedRealtimeConfigGrpcServiceServer) testEmbeddedByValue() {}

// UnsafeRealtimeConfigGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RealtimeConfigGrpcServiceServer will
// result in compilation errors.
type UnsafeRealtimeConfigGrpcServiceServer interface {
	mustEmbedUnimplementedRealtimeConfigGrpcServiceServer()
}

func RegisterRealtimeConfigGrpcServiceServer(s grpc.ServiceRegistrar, srv RealtimeConfigGrpcServiceServer) {
	// If the following call panics, it indicates UnimplementedRealtimeConfigGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RealtimeConfigGrpcService_ServiceDesc, srv)
}

func _RealtimeConfigGrpcService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeConfigGrpcServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeConfigGrpcService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeConfigGrpcServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealtimeConfigGrpcService_IsVersionExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsVersionExistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeConfigGrpcServiceServer).IsVersionExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeConfigGrpcService_IsVersionExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeConfigGrpcServiceServer).IsVersionExists(ctx, req.(*IsVersionExistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealtimeConfigGrpcService_CreateVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeConfigGrpcServiceServer).CreateVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeConfigGrpcService_CreateVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeConfigGrpcServiceServer).CreateVersion(ctx, req.(*CreateVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealtimeConfigGrpcService_StartSubscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartSubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RealtimeConfigGrpcServiceServer).StartSubscribe(m, &grpc.GenericServerStream[StartSubscribeRequest, SubscriptionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RealtimeConfigGrpcService_StartSubscribeServer = grpc.ServerStreamingServer[SubscriptionEvent]

// RealtimeConfigGrpcService_ServiceDesc is the grpc.ServiceDesc for RealtimeConfigGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RealtimeConfigGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "konfigo.client.RealtimeConfigGrpcService",
	HandlerType: (*RealtimeConfigGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _RealtimeConfigGrpcService_GetConfig_Handler,
		},
		{
			MethodName: "IsVersionExists",
			Handler:    _RealtimeConfigGrpcService_IsVersionExists_Handler,
		},
		{
			MethodName: "CreateVersion",
			Handler:    _RealtimeConfigGrpcService_CreateVersion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartSubscribe",
			Handler:       _RealtimeConfigGrpcService_StartSubscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
