// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValueType int32

const (
	ValueType_VALUE_TYPE_UNKNOWN   ValueType = 0
	ValueType_VALUE_TYPE_STRING    ValueType = 1
	ValueType_VALUE_TYPE_BOOLEAN   ValueType = 2
	ValueType_VALUE_TYPE_DATE_TIME ValueType = 3
	ValueType_VALUE_TYPE_TIME_SPAN ValueType = 4
	ValueType_VALUE_TYPE_ENUM      ValueType = 5
	ValueType_VALUE_TYPE_NUMBER    ValueType = 6
	ValueType_VALUE_TYPE_ARRAY     ValueType = 7
	ValueType_VALUE_TYPE_JSON      ValueType = 8
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0: "VALUE_TYPE_UNKNOWN",
		1: "VALUE_TYPE_STRING",
		2: "VALUE_TYPE_BOOLEAN",
		3: "VALUE_TYPE_DATE_TIME",
		4: "VALUE_TYPE_TIME_SPAN",
		5: "VALUE_TYPE_ENUM",
		6: "VALUE_TYPE_NUMBER",
		7: "VALUE_TYPE_ARRAY",
		8: "VALUE_TYPE_JSON",
	}
	ValueType_value = map[string]int32{
		"VALUE_TYPE_UNKNOWN":   0,
		"VALUE_TYPE_STRING":    1,
		"VALUE_TYPE_BOOLEAN":   2,
		"VALUE_TYPE_DATE_TIME": 3,
		"VALUE_TYPE_TIME_SPAN": 4,
		"VALUE_TYPE_ENUM":      5,
		"VALUE_TYPE_NUMBER":    6,
		"VALUE_TYPE_ARRAY":     7,
		"VALUE_TYPE_JSON":      8,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetConfigRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GetConfigRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetConfigResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Entries       []*GetConfigResponse_ConfigEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigResponse) GetEntries() []*GetConfigResponse_ConfigEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type IsVersionExistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsVersionExistRequest) Reset() {
	*x = IsVersionExistRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsVersionExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsVersionExistRequest) ProtoMessage() {}

func (x *IsVersionExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsVersionExistRequest.ProtoReflect.Descriptor instead.
func (*IsVersionExistRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *IsVersionExistRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *IsVersionExistRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type IsVersionExistResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	VersionId     *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsVersionExistResponse) Reset() {
	*x = IsVersionExistResponse{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsVersionExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsVersionExistResponse) ProtoMessage() {}

func (x *IsVersionExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsVersionExistResponse.ProtoReflect.Descriptor instead.
func (*IsVersionExistResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *IsVersionExistResponse) GetVersionId() *wrapperspb.StringValue {
	if x != nil {
		return x.VersionId
	}
	return nil
}

type CreateVersionRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	ServiceId     string                             `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Version       string                             `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Classes       []*CreateVersionRequest_ClassEntry `protobuf:"bytes,3,rep,name=classes,proto3" json:"classes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVersionRequest) Reset() {
	*x = CreateVersionRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionRequest) ProtoMessage() {}

func (x *CreateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionRequest.ProtoReflect.Descriptor instead.
func (*CreateVersionRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVersionRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *CreateVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateVersionRequest) GetClasses() []*CreateVersionRequest_ClassEntry {
	if x != nil {
		return x.Classes
	}
	return nil
}

type CreateVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionId     string                 `protobuf:"bytes,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVersionResponse) Reset() {
	*x = CreateVersionResponse{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionResponse) ProtoMessage() {}

func (x *CreateVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionResponse.ProtoReflect.Descriptor instead.
func (*CreateVersionResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateVersionResponse) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

type StartSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	VersionId     string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSubscribeRequest) Reset() {
	*x = StartSubscribeRequest{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSubscribeRequest) ProtoMessage() {}

func (x *StartSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSubscribeRequest.ProtoReflect.Descriptor instead.
func (*StartSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *StartSubscribeRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *StartSubscribeRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *StartSubscribeRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type SubscriptionEvent struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Events        []*SubscriptionEvent_ConfigEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionEvent) Reset() {
	*x = SubscriptionEvent{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionEvent) ProtoMessage() {}

func (x *SubscriptionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionEvent.ProtoReflect.Descriptor instead.
func (*SubscriptionEvent) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *SubscriptionEvent) GetEvents() []*SubscriptionEvent_ConfigEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetConfigResponse_ConfigEntry struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Key           string                  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Generation    int32                   `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Timestamp     *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse_ConfigEntry) Reset() {
	*x = GetConfigResponse_ConfigEntry{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse_ConfigEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse_ConfigEntry) ProtoMessage() {}

func (x *GetConfigResponse_ConfigEntry) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse_ConfigEntry.ProtoReflect.Descriptor instead.
func (*GetConfigResponse_ConfigEntry) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetConfigResponse_ConfigEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetConfigResponse_ConfigEntry) GetValue() *wrapperspb.StringValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetConfigResponse_ConfigEntry) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *GetConfigResponse_ConfigEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CreateVersionRequest_ClassEntry struct {
	state         protoimpl.MessageState                         `protogen:"open.v1"`
	Name          string                                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *wrapperspb.StringValue                        `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Entries       []*CreateVersionRequest_ClassEntry_ConfigEntry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVersionRequest_ClassEntry) Reset() {
	*x = CreateVersionRequest_ClassEntry{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVersionRequest_ClassEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionRequest_ClassEntry) ProtoMessage() {}

func (x *CreateVersionRequest_ClassEntry) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionRequest_ClassEntry.ProtoReflect.Descriptor instead.
func (*CreateVersionRequest_ClassEntry) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CreateVersionRequest_ClassEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVersionRequest_ClassEntry) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *CreateVersionRequest_ClassEntry) GetEntries() []*CreateVersionRequest_ClassEntry_ConfigEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CreateVersionRequest_ClassEntry_ConfigEntry struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Key           string                  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ValueType     ValueType               `protobuf:"varint,4,opt,name=value_type,json=valueType,proto3,enum=konfigo.client.ValueType" json:"value_type,omitempty"`
	EnumValues    *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"`
	Value         *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVersionRequest_ClassEntry_ConfigEntry) Reset() {
	*x = CreateVersionRequest_ClassEntry_ConfigEntry{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVersionRequest_ClassEntry_ConfigEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionRequest_ClassEntry_ConfigEntry) ProtoMessage() {}

func (x *CreateVersionRequest_ClassEntry_ConfigEntry) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionRequest_ClassEntry_ConfigEntry.ProtoReflect.Descriptor instead.
func (*CreateVersionRequest_ClassEntry_ConfigEntry) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *CreateVersionRequest_ClassEntry_ConfigEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateVersionRequest_ClassEntry_ConfigEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVersionRequest_ClassEntry_ConfigEntry) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *CreateVersionRequest_ClassEntry_ConfigEntry) GetValueType() ValueType {
	if x != nil {
		return x.ValueType
	}
	return ValueType_VALUE_TYPE_UNKNOWN
}

func (x *CreateVersionRequest_ClassEntry_ConfigEntry) GetEnumValues() *wrapperspb.StringValue {
	if x != nil {
		return x.EnumValues
	}
	return nil
}

func (x *CreateVersionRequest_ClassEntry_ConfigEntry) GetValue() *wrapperspb.StringValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type SubscriptionEvent_ConfigEvent struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Key           string                  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Generation    int32                   `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Timestamp     *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionEvent_ConfigEvent) Reset() {
	*x = SubscriptionEvent_ConfigEvent{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionEvent_ConfigEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionEvent_ConfigEvent) ProtoMessage() {}

func (x *SubscriptionEvent_ConfigEvent) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionEvent_ConfigEvent.ProtoReflect.Descriptor instead.
func (*SubscriptionEvent_ConfigEvent) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7, 0}
}

func (x *SubscriptionEvent_ConfigEvent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SubscriptionEvent_ConfigEvent) GetValue() *wrapperspb.StringValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SubscriptionEvent_ConfigEvent) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *SubscriptionEvent_ConfigEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x0ekonfigo.client\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"K\n" +
	"\x10GetConfigRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x8c\x02\n" +
	"\x11GetConfigResponse\x12G\n" +
	"\aentries\x18\x01 \x03(\v2-.konfigo.client.GetConfigResponse.ConfigEntryR\aentries\x1a\xad\x01\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x05value\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x05R\n" +
	"generation\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"P\n" +
	"\x15IsVersionExistRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"U\n" +
	"\x16IsVersionExistResponse\x12;\n" +
	"\n" +
	"version_id\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\tversionId\"\xf7\x04\n" +
	"\x14CreateVersionRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12I\n" +
	"\aclasses\x18\x03 \x03(\v2/.konfigo.client.CreateVersionRequest.ClassEntryR\aclasses\x1a\xda\x03\n" +
	"\n" +
	"ClassEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12>\n" +
	"\vdescription\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12U\n" +
	"\aentries\x18\x03 \x03(\v2;.konfigo.client.CreateVersionRequest.ClassEntry.ConfigEntryR\aentries\x1a\xa0\x02\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12>\n" +
	"\vdescription\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x128\n" +
	"\n" +
	"value_type\x18\x04 \x01(\x0e2\x19.konfigo.client.ValueTypeR\tvalueType\x12=\n" +
	"\venum_values\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"enumValues\x122\n" +
	"\x05value\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x05value\"6\n" +
	"\x15CreateVersionResponse\x12\x1d\n" +
	"\n" +
	"version_id\x18\x01 \x01(\tR\tversionId\"\x8f\x01\n" +
	"\x15StartSubscribeRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x8a\x02\n" +
	"\x11SubscriptionEvent\x12E\n" +
	"\x06events\x18\x01 \x03(\v2-.konfigo.client.SubscriptionEvent.ConfigEventR\x06events\x1a\xad\x01\n" +
	"\vConfigEvent\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x05value\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x05R\n" +
	"generation\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*\xdd\x01\n" +
	"\tValueType\x12\x16\n" +
	"\x12VALUE_TYPE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11VALUE_TYPE_STRING\x10\x01\x12\x16\n" +
	"\x12VALUE_TYPE_BOOLEAN\x10\x02\x12\x18\n" +
	"\x14VALUE_TYPE_DATE_TIME\x10\x03\x12\x18\n" +
	"\x14VALUE_TYPE_TIME_SPAN\x10\x04\x12\x13\n" +
	"\x0fVALUE_TYPE_ENUM\x10\x05\x12\x15\n" +
	"\x11VALUE_TYPE_NUMBER\x10\x06\x12\x14\n" +
	"\x10VALUE_TYPE_ARRAY\x10\a\x12\x13\n" +
	"\x0fVALUE_TYPE_JSON\x10\b2\x8b\x03\n" +
	"\x19RealtimeConfigGrpcService\x12P\n" +
	"\tGetConfig\x12 .konfigo.client.GetConfigRequest\x1a!.konfigo.client.GetConfigResponse\x12`\n" +
	"\x0fIsVersionExists\x12%.konfigo.client.IsVersionExistRequest\x1a&.konfigo.client.IsVersionExistResponse\x12\\\n" +
	"\rCreateVersion\x12$.konfigo.client.CreateVersionRequest\x1a%.konfigo.client.CreateVersionResponse\x12\\\n" +
	"\x0eStartSubscribe\x12%.konfigo.client.StartSubscribeRequest\x1a!.konfigo.client.SubscriptionEvent0\x01BCZAgithub.com/maximiliysiss/konfigo/packages/go/internal/proto;protob\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_service_proto_goTypes = []any{
	(ValueType)(0),                                      // 0: konfigo.client.ValueType
	(*GetConfigRequest)(nil),                            // 1: konfigo.client.GetConfigRequest
	(*GetConfigResponse)(nil),                           // 2: konfigo.client.GetConfigResponse
	(*IsVersionExistRequest)(nil),                       // 3: konfigo.client.IsVersionExistRequest
	(*IsVersionExistResponse)(nil),                      // 4: konfigo.client.IsVersionExistResponse
	(*CreateVersionRequest)(nil),                        // 5: konfigo.client.CreateVersionRequest
	(*CreateVersionResponse)(nil),                       // 6: konfigo.client.CreateVersionResponse
	(*StartSubscribeRequest)(nil),                       // 7: konfigo.client.StartSubscribeRequest
	(*SubscriptionEvent)(nil),                           // 8: konfigo.client.SubscriptionEvent
	(*GetConfigResponse_ConfigEntry)(nil),               // 9: konfigo.client.GetConfigResponse.ConfigEntry
	(*CreateVersionRequest_ClassEntry)(nil),             // 10: konfigo.client.CreateVersionRequest.ClassEntry
	(*CreateVersionRequest_ClassEntry_ConfigEntry)(nil), // 11: konfigo.client.CreateVersionRequest.ClassEntry.ConfigEntry
	(*SubscriptionEvent_ConfigEvent)(nil),               // 12: konfigo.client.SubscriptionEvent.ConfigEvent
	(*wrapperspb.StringValue)(nil),                      // 13: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),                       // 14: google.protobuf.Timestamp
}
var file_service_proto_depIdxs = []int32{
	9,  // 0: konfigo.client.GetConfigResponse.entries:type_name -> konfigo.client.GetConfigResponse.ConfigEntry
	13, // 1: konfigo.client.IsVersionExistResponse.version_id:type_name -> google.protobuf.StringValue
	10, // 2: konfigo.client.CreateVersionRequest.classes:type_name -> konfigo.client.CreateVersionRequest.ClassEntry
	14, // 3: konfigo.client.StartSubscribeRequest.timestamp:type_name -> google.protobuf.Timestamp
	12, // 4: konfigo.client.SubscriptionEvent.events:type_name -> konfigo.client.SubscriptionEvent.ConfigEvent
	13, // 5: konfigo.client.GetConfigResponse.ConfigEntry.value:type_name -> google.protobuf.StringValue
	14, // 6: konfigo.client.GetConfigResponse.ConfigEntry.timestamp:type_name -> google.protobuf.Timestamp
	13, // 7: konfigo.client.CreateVersionRequest.ClassEntry.description:type_name -> google.protobuf.StringValue
	11, // 8: konfigo.client.CreateVersionRequest.ClassEntry.entries:type_name -> konfigo.client.CreateVersionRequest.ClassEntry.ConfigEntry
	13, // 9: konfigo.client.CreateVersionRequest.ClassEntry.ConfigEntry.description:type_name -> google.protobuf.StringValue
	0,  // 10: konfigo.client.CreateVersionRequest.ClassEntry.ConfigEntry.value_type:type_name -> konfigo.client.ValueType
	13, // 11: konfigo.client.CreateVersionRequest.ClassEntry.ConfigEntry.enum_values:type_name -> google.protobuf.StringValue
	13, // 12: konfigo.client.CreateVersionRequest.ClassEntry.ConfigEntry.value:type_name -> google.protobuf.StringValue
	13, // 13: konfigo.client.SubscriptionEvent.ConfigEvent.value:type_name -> google.protobuf.StringValue
	14, // 14: konfigo.client.SubscriptionEvent.ConfigEvent.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 15: konfigo.client.RealtimeConfigGrpcService.GetConfig:input_type -> konfigo.client.GetConfigRequest
	3,  // 16: konfigo.client.RealtimeConfigGrpcService.IsVersionExists:input_type -> konfigo.client.IsVersionExistRequest
	5,  // 17: konfigo.client.RealtimeConfigGrpcService.CreateVersion:input_type -> konfigo.client.CreateVersionRequest
	7,  // 18: konfigo.client.RealtimeConfigGrpcService.StartSubscribe:input_type -> konfigo.client.StartSubscribeRequest
	2,  // 19: konfigo.client.RealtimeConfigGrpcService.GetConfig:output_type -> konfigo.client.GetConfigResponse
	4,  // 20: konfigo.client.RealtimeConfigGrpcService.IsVersionExists:output_type -> konfigo.client.IsVersionExistResponse
	6,  // 21: konfigo.client.RealtimeConfigGrpcService.CreateVersion:output_type -> konfigo.client.CreateVersionResponse
	8,  // 22: konfigo.client.RealtimeConfigGrpcService.StartSubscribe:output_type -> konfigo.client.SubscriptionEvent
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
