# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RealtimeConfigGrpcServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConfig = channel.unary_unary(
                '/konfigo.client.RealtimeConfigGrpcService/GetConfig',
                request_serializer=service__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=service__pb2.GetConfigResponse.FromString,
                _registered_method=True)
        self.IsVersionExists = channel.unary_unary(
                '/konfigo.client.RealtimeConfigGrpcService/IsVersionExists',
                request_serializer=service__pb2.IsVersionExistRequest.SerializeToString,
                response_deserializer=service__pb2.IsVersionExistResponse.FromString,
                _registered_method=True)
        self.CreateVersion = channel.unary_unary(
                '/konfigo.client.RealtimeConfigGrpcService/CreateVersion',
                request_serializer=service__pb2.CreateVersionRequest.SerializeToString,
                response_deserializer=service__pb2.CreateVersionResponse.FromString,
                _registered_method=True)
        self.StartSubscribe = channel.unary_stream(
                '/konfigo.client.RealtimeConfigGrpcService/StartSubscribe',
                request_serializer=service__pb2.StartSubscribeRequest.SerializeToString,
                response_deserializer=service__pb2.SubscriptionEvent.FromString,
                _registered_method=True)


class RealtimeConfigGrpcServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsVersionExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RealtimeConfigGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=service__pb2.GetConfigRequest.FromString,
                    response_serializer=service__pb2.GetConfigResponse.SerializeToString,
            ),
            'IsVersionExists': grpc.unary_unary_rpc_method_handler(
                    servicer.IsVersionExists,
                    request_deserializer=service__pb2.IsVersionExistRequest.FromString,
                    response_serializer=service__pb2.IsVersionExistResponse.SerializeToString,
            ),
            'CreateVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVersion,
                    request_deserializer=service__pb2.CreateVersionRequest.FromString,
                    response_serializer=service__pb2.CreateVersionResponse.SerializeToString,
            ),
            'StartSubscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.StartSubscribe,
                    request_deserializer=service__pb2.StartSubscribeRequest.FromString,
                    response_serializer=service__pb2.SubscriptionEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'konfigo.client.RealtimeConfigGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('konfigo.client.RealtimeConfigGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RealtimeConfigGrpcService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/konfigo.client.RealtimeConfigGrpcService/GetConfig',
            service__pb2.GetConfigRequest.SerializeToString,
            service__pb2.GetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsVersionExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/konfigo.client.RealtimeConfigGrpcService/IsVersionExists',
            service__pb2.IsVersionExistRequest.SerializeToString,
            service__pb2.IsVersionExistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/konfigo.client.RealtimeConfigGrpcService/CreateVersion',
            service__pb2.CreateVersionRequest.SerializeToString,
            service__pb2.CreateVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/konfigo.client.RealtimeConfigGrpcService/StartSubscribe',
            service__pb2.StartSubscribeRequest.SerializeToString,
            service__pb2.SubscriptionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
