name: konfigo

services:
    nginx:
        image: nginx:1.27-alpine
        ports:
            - "3000:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - dex
            - mock-oauth2
            - saml-idp

    postgres:
        image: postgres:14
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: konfigo
            POSTGRES_PASSWORD: pwd
            POSTGRES_USER: postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d konfigo"]
            interval: 5s
            timeout: 5s
            retries: 20

    redis:
        image: redis:7.0.6-alpine
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 20

    dex:
        image: ghcr.io/dexidp/dex:v2.41.1
        command: ["dex", "serve", "/etc/dex/config.yaml"]
        ports:
            - "5556:5556"
        volumes:
            - ./docker/dex/config.yaml:/etc/dex/config.yaml:ro

    mock-oauth2:
        image: ghcr.io/navikt/mock-oauth2-server:latest
        ports:
            - "8082:8080"
        volumes:
            - ./docker/mock-oauth2/config.json:/app/config.json:ro
        environment:
            JSON_CONFIG_PATH: /app/config.json

    saml-idp:
        image: druidfi/saml-idp:2.4.4
        ports:
            - "4000:8080"
            - "4001:8443"
        environment:
            SIMPLESAMLPHP_IDP_BASEURLPATH: http://localhost:3000/saml2/simplesaml/
            SIMPLESAMLPHP_SP_ENTITY_ID: http://localhost:3000/saml2/Metadata
            SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:3000/saml2/Acs
            SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost:3000/saml2/Logout
        volumes:
            - ./docker/saml-config/authsources.php:/app/simplesamlphp/config/authsources.php
